<?php

return [
    "title" => "Nuestras Historias",
    "post1" => [
        "title" => "Día de la Maestra - Aleyda Machán",
        "paragraph1" => "Aleyda de las Mercedes Machan Sosa es una maestra empática y de actitud de positiva, ella expresa a través de su rostro, tono de voz y lenguaje corporal una ternura que invita a los niños a sentir confianza, estableciendo el ambiente ideal para el aprendizaje.",
        "paragraph2" => "Aleyda se convirtió en maestra en nuestro preescolar de San Lucas el año pasado. Su vocación como maestra y su amor por la educación infantil han brillado durante su tiempo en Plantando Semillas. Ella recuerda que siempre quiso ser maestra de preescolar, incluso cuando ella era una niña.",
        "paragraph3" => "Cuando era pequeña solía organizar actividades de aprendizaje y juegos con otros niños, ya fueran sus hermanos, primos, compañeros de clase o vecinos. Incluso recuerda jugar a ser la maestra de los conejitos que tenía en su casa. A los 13 años, supo que quería ser maestra de preescolar porque le gustaba jugar, cantar y bailar con los niños pequeños.",
        "paragraph4" => "Cuando creció, estudió en un colegio en Antigua para ser maestra de preescolar. Poco después de graduarse, comenzó a desarrollar experiencia en diferentes escuelas, trabajando tanto con niños pequeños como con adolescentes. Fue directora del Núcleo de Desarrollo Familiar, donde trabajó principalmente en la formación profesional para adolescentes. Sin embargo, en el fondo de su corazón, sabía que su principal pasión era trabajar en la educación infantil.",
        "paragraph5" => "Cuando comenzó a trabajar con la Metodología Plantando Semillas, se dio cuenta de la importancia de educar a través de un enfoque holístico centrado en la familia, lo cuál  no había encontrado en ninguna otra escuela en Guatemala. En su opinión, una de las mejores partes de la metodología es utilizar un marco positivo para apoyar el comportamiento de los niños en lugar de centrarse en lo que no deberían estar haciendo, que es algo que prevalece en otros sistemas escolares.",
        "paragraph6" => "Aleyda disfruta cantar y bailar con sus alumnos. Le encanta verlos reír y divertirse. También le encanta cuando sus alumnos logran algo que les ha costado un tiempo aprender.",
        "paragraph7" => "Para ella, un buen maestro nace del corazón. Cuando un niño, un joven o un adulto logra algo, también debemos considerarlo como el logro de los profesores que abrieron el camino para su aprendizaje.",
        "paragraph8" => "¡Estamos felices de tener a Aleyda y tantas otras maravillosas y apasionadas maestras trabajando con nosotros! Gracias a todos los profesores que nos han enseñado a lo largo de nuestras vidas, ¡no seríamos los mismos sin ustedes!",
    ], 
    "post2" => [
        "title" => "Compartiendo el Amor por la Lectura",
        "paragraph1" => "En 2019, a través del esfuerzo combinado de organizaciones asociadas y donantes, Plantando Semillas inauguró una Biblioteca Comunitaria en la Zona 3 de la Ciudad de Guatemala con el objetivo de compartir el amor por la lectura tanto con los participantes de nuestros programas como con los miembros de la comunidad. El programa consiste en proporcionar un lugar seguro donde todos puedan venir a leer y también ofrecemos un programa de préstamo de libros. En unos pocos años, esta biblioteca comunitaria se ha transformado en un espacio que brinda acceso a libros no solo a la Zona 3, sino a todos los preescolares de Plantando Semillas.",
        "paragraph2" => "Esta transformación comenzó en 2019, cuando lanzamos nuestras capacitaciones &#34Lea con su hijo&#34  para las madres y padres de nuestros centros preescolares para mejorar las habilidades de educación temprana y ayudar a fomentar las relaciones entre padres e hijos. Acompañamos estas capacitaciones con un programa semanal de préstamo de libros en nuestra escuelita modelo en San Lucas. Ahora, en 2021, comenzamos el año realizando encuestas en los centros preescolares para conocer las barreras que tenían los padres para tomar un papel activo en la educación de sus hijos. Los principales factores compartidos por los padres fueron la falta de experiencia, confianza y acceso a los libros.",
        "paragraph3" => "Para combatir la falta de experiencia y confianza que los padres expresaron en la encuesta, comenzamos a brindar capacitaciones para padres basadas en la práctica en nuestros centros preescolares. Estas capacitaciones son extremadamente intencionales y se enfocan en brindarles a los padres habilidades prácticas y la oportunidad de practicar esas habilidades con los maestros y otros padres. En nuestro taller de “creación de pequeños lectores”, todos los padres se asociaron y practicaron la lectura entre ellos como si el otro padre fuera su hijo. Luego, los padres recibieron comentarios en persona de los maestros. Aunque muchos padres presentan dificultades para leer o escribir ellos mismos, nuestras capacitaciones se enfocan en apoyar la habilidad de los padres para leer con sus hijos, contando historias a través de imágenes, adaptándose a las diferentes necesidades de todos los padres de Plantando Semillas.",
        "paragraph4" => "Además de estas capacitaciones, hemos comenzado a expandir el programa de préstamo de libros de nuestra Biblioteca de la Zona 3 para combatir la falta de acceso a los libros en nuestras comunidades rurales. Ahora, los estudiantes de Plantando Semillas pueden pedir prestados cuatro libros al mes. Al final de cada mes, los padres devuelven los libros y los padres traen a casa un nuevo set de libros. Las familias de Plantando Semillas están muy agradecidas por este programa.",
        "paragraph5" => "Este crecimiento en nuestra programación se debe a nuestras educadoras increíblemente apasionadas, familias abiertas y trabajadoras y, la generosidad de nuestros donantes. Gracias por todo su apoyo. <br><br> Si tiene la capacidad, su ayuda continua puede proporcionar libros a las familias a través de nuestra biblioteca comunitaria y la capacitación necesaria para ayudar a los padres a desarrollar el amor por la lectura en sus hogares.",
    ], 
    "post3" => [
        "title" => "Apoyando a madres, padres y estudiantes",
        "paragraph1" => "&#34 Me siento muy contenta, muy ansiosa de poder ver a mis estudiantes, de poder compartir con ellas y ellos, aunque sea por unos minutos debido a la situación. Me siento muy motivada por continuar brindándole más apoyo a mis estudiantes y, seguir ayudando a las niñas y niños que, en su momento observe que necesitaban más atención y que tenían dificultades de aprendizaje y, que muchas veces en casa no se les proporcionan las clases de la misma manera en que yo se las brindo &#34; -  <strong>Helen Chacón</strong>, maestra en el preescolar &#34Jardín Semillas de Esperanza&#34 en Tioxyá, Chimaltenango.",
        "paragraph2" => "Las maestras de Plantando Semillas han pasado por muchas emociones durante el año 2020. ¡Estamos increíblemente orgullosos de ellas! No solo se adaptaron a las nuevas condiciones laborales en un tiempo récord, sino que han continuado poniendo su corazón en todo lo que hacen para asegurar que nuestros estudiantes sigan aprendiendo a pesar de las diferentes condiciones desafiantes que seguimos encontrando.",
        "paragraph3" => "Durante el último año, hemos sido testigos de un cambio significativo en la participación de las madres en la educación de sus hijos. Helen Chacón, nuestra maestra en el preescolar ubicado en Tioxya, dice que muchas de las madres con las que trabaja no tuvieron acceso a educación; sin embargo, se han esforzado mucho para ayudar a sus hijos. Como maestra, Helen está muy motivada para ayudar a las madres a tener éxito y convertirse en mentoras para sus hijos. Ser maestra en estas circunstancias no es tarea fácil. No todo el mundo cuenta con las condiciones adecuadas para llevar a cabo el aprendizaje a distancia, por lo que ha sido complicado conseguir que todas las actividades e información se entreguen tanto a los alumnos como a las madres de la mejor forma posible. Sin embargo, de una forma u otra, nuestras maestras han encontrado alternativas para apoyar a todos los hogares. <br><br>Helen dice que muchas madres se han vuelto más pacientes y están dispuestas a dirigir actividades educativas con sus hijos. Estamos muy emocionados de tomar esto como una oportunidad para ayudar a las madres a desarrollar las habilidades necesarias para convertirse en las educadoras principales de sus hijas e hijos.",
        "paragraph4" => "",
    ], 
    
    
];