<?php

return [
    "title" => "Nuestras Historias",
    "post1" => [
        "title" => "Día del Maestro - Aleyda Machán",
        "paragraph1" => "Aleyda de las Mercedes Machan Sosa es una docente empática que encarna una actitud de positividad, expresando a través de su rostro, tono de voz y lenguaje corporal una ternura que invita a los niños a sentir confianza, configurando el ambiente ideal para el aprendizaje.",
        "paragraph2" => "Aleyda se convirtió en maestra en nuestro preescolar de San Lucas el año pasado. Su vocación como maestra y amor por la educación infantil han brillado durante su paso por Planting Seeds. Recuerda que siempre quiso ser maestra de preescolar, incluso cuando ella misma era una niña.",
        "paragraph3" => "Cuando era pequeña, organizaba actividades de aprendizaje y juegos con otros niños, ya fueran sus hermanos, primos, compañeros de clase o vecinos. Incluso recuerda jugar a ser la maestra de los conejitos que tenía en su casa. A los 13 años supo que quería ser maestra de preescolar porque le gustaba jugar, cantar y bailar con los niños pequeños.",
        "paragraph4" => "Cuando creció, se matriculó en una universidad en Antigua para convertirse en maestra de preescolar. Poco después de graduarse, adquirió experiencia en diferentes escuelas, trabajando tanto con niños pequeños como con adolescentes. Fue directora de un Centro de Desarrollo Familiar, donde se desempeñó principalmente en la formación profesional de adolescentes. Sin embargo, en el fondo de su corazón, sabía que su principal pasión era trabajar en la educación infantil.",
        "paragraph5" => "Cuando comenzó a trabajar con la Metodología Sembrando Semillas, se dio cuenta de la importancia de educar a través de un enfoque holístico centrado en la familia, que no había encontrado en ninguna otra escuela en Guatemala. En su opinión, una de las mejores partes de la metodología es utilizar un marco positivo para apoyar el comportamiento de los niños en lugar de centrarse en lo que no deberían estar haciendo, algo que prevalece en otros sistemas escolares.",
        "paragraph6" => "Aleyda disfruta cantar y bailar con sus alumnos. Le encanta verlos reír y divertirse. También le encanta cuando sus alumnos logran algo que les ha llevado tiempo aprender.",
        "paragraph7" => "Para ella, un buen maestro nace del corazón. Cuando un niño, un joven o un adulto logra algo, también debemos considerarlo como un logro de los maestros que allanaron el camino para su aprendizaje.",
        "paragraph8" => "¡Estamos felices de tener a Aleyda y a tantos otros maestros maravillosos y apasionados trabajando con nosotros! ¡Gracias a todos los maestros que nos han enseñado a lo largo de nuestra vida, sin ustedes no seríamos lo mismo!",
    ], 
    "post2" => [
        "title" => "Compartiendo el amor por la lectura",
        "paragraph1" => "En 2019, a través del esfuerzo combinado de organizaciones asociadas y colaboradores increíbles, Planting Seeds abrió una Biblioteca Comunitaria en la Zona 3 de la Ciudad de Guatemala con el objetivo de compartir el amor por la lectura con los participantes de nuestro programa y miembros de la comunidad por igual. El programa consiste en proporcionar un lugar seguro donde todos puedan venir a leer y un programa líder en libros. En unos pocos años, esta Biblioteca Comunitaria se ha transformado para brindar acceso a libros no solo a la Zona 3, sino a todos los preescolares de Planting Seeds.",
        "paragraph2" => "Esta transformación comenzó en 2019, cuando lanzamos nuestras capacitaciones &#34Lea con su hijo&#34 para los padres en nuestros preescolares para mejorar las habilidades de alfabetización temprana y ayudar a fomentar las relaciones entre padres e hijos. Acompañamos estas capacitaciones con un programa semanal de préstamo de libros en nuestra escuela modelo en San Lucas. Ahora en 2021, comenzamos el año realizando encuestas en los preescolares para conocer las barreras que tenían los padres para tomar un rol activo en la educación de sus hijos. Los principales factores informados por los padres fueron la falta de experiencia, confianza y acceso a libros.",
        "paragraph3" => "Para combatir la falta de experiencia y confianza que los padres expresaron en la encuesta, comenzamos a brindar capacitaciones para padres en nuestras escuelas preescolares. Estas capacitaciones son extremadamente intencionales y se enfocan en brindarles a los padres habilidades prácticas y la oportunidad de practicar esas habilidades con los maestros y otros padres. En nuestro taller de &#34creación de pequeños lectores&#34, todos los padres se asociaron y practicaron la lectura entre ellos como si el otro padre fuera su hijo. Luego, los padres recibieron comentarios en persona de los maestros. Aunque muchos padres presentan dificultades para leer o escribir, nuestras capacitaciones se enfocan en apoyar la habilidad de los padres para leer con sus hijos, contando historias a través de imágenes, adaptándose a las diferentes necesidades de todos los padres de Planting Seeds.",
        "paragraph4" => "Además de estas capacitaciones, hemos comenzado a expandir el programa de préstamo de libros de nuestra Biblioteca de la Zona 3 para combatir la falta de acceso a libros en nuestras comunidades rurales. Ahora, los estudiantes de Planting Seeds pueden pedir prestados cuatro libros al mes. Al final de cada mes, los padres devuelven los libros y los padres devuelven los libros y los padres traen un juego nuevo. Planting Seeds está muy agradecido por este programa.",
        "paragraph5" => "Este crecimiento en nuestra programación se debe a nuestros educadores increíblemente apasionados, familias abiertas y trabajadoras y su generosidad. Gracias por todo su apoyo. Si tiene la capacidad, su ayuda continua puede proporcionar libros a las familias a través de nuestra Biblioteca Comunitaria y la capacitación necesaria para ayudar a los padres a desarrollar un amor por la lectura en sus hogares.",
    ], 
    "post3" => [
        "title" => "Tutoría de padres y estudiantes",
        "paragraph1" => "&#34Me emociona volver a ver a mis alumnos, incluso si solo será por un par de días a la semana. Creo que esto será especialmente útil para ciertos alumnos que han tenido muchas dificultades con el aprendizaje remoto. Me siento feliz de que tendremos la oportunidad de trabajar juntos en el salón de clases y debo guiar tanto a los estudiantes como a los padres. Creo que asesorar a los padres será beneficioso para reforzar las lecciones que nuestros estudiantes aprenden en casa.&#34<br><br>&#34-Helen Chacón, maestra de preescolar en &#34Garden Seeds of Hope&#34",
        "paragraph2" => "Los maestros de Planting Seeds han pasado por una montaña rusa de emociones durante el último año. ¡Estamos increíblemente orgullosos de ellos! No solo se adaptaron a las nuevas condiciones de trabajo en un tiempo récord, sino que han seguido volcando su corazón en su trabajo para garantizar que nuestros estudiantes sigan aprendiendo a pesar de las diferentes condiciones desafiantes que seguimos encontrando.",
        "paragraph3" => "Durante el último año, hemos sido testigos de un cambio significativo en la participación de los padres en la educación de sus hijos. Helen Chacón, una de nuestras maestras de preescolar en Tioxya, dice que muchos de los padres con los que trabaja no saben leer ni escribir; sin embargo, han puesto mucho empeño en ayudar a sus hijos. Como maestra, Helen está muy motivada para ayudar a los padres a tener éxito y convertirse en mentores efectivos para sus hijos. Ser docente en estas circunstancias no es tarea fácil. No todos cuentan con las condiciones más adecuadas para llevar a cabo el aprendizaje a distancia, por lo que ha sido difícil garantizar que todas las actividades e información se entreguen tanto a los estudiantes como a los padres de la mejor manera posible. Sin embargo, de una forma u otra, nuestros maestros han encontrado alternativas para apoyar a todos los hogares.",
        "paragraph4" => "Helen dice que muchos padres se han vuelto más pacientes y dispuestos a dirigir actividades educativas con sus hijos. Estamos muy emocionados de tomar esto como una oportunidad para ayudar a los padres a desarrollar las habilidades necesarias para convertirse en los principales educadores de sus hijos.",
    ], 
    
    
];