<?php

return [
    "title" => "Our stories",
    "post1" => [
        "title" => "Our Impact",
        "paragraph1" => "Aleyda de las Mercedes Machan Sosa is an empathetic teacher who embodies an attitude of positivity, expressing through her face, tone of voice and body language a tenderness that invites children to feel trust, setting the ideal environment for learning.",
        "paragraph2" => "Aleyda became a teacher in our San Lucas preschool last year. Her vocation as a teacher and love for early childhood education have shined during her time at Planting Seeds. She recalls always wanting to be a preschool teacher, even when she was a kid herself.",
        "paragraph3" => "When she was little, she used to organize learning activities and games with other children, being her siblings, cousins, classmates or neighbors. She even remembers playing to be the teacher of the bunnies she had in her house. At age 13, she knew she wanted to become a preschool teacher because she liked playing, singing and dancing with little children.",
        "paragraph4" => "When she grew up, she enrolled in a college in Antigua to become a preschool teacher. Soon after she graduated, she gained experience in different schools, working with both small children and teenagers. She was director of a Center for Family Development, where she mainly worked in vocational training for teenagers. However, deep in her heart, she knew that her main passion was working in early childhood education.",
        "paragraph5" => "When she began working with the Planting Seeds Methodology, she realized the importance of educating through a holistic family-centered approach, which she had not encountered in any other school in Guatemala. In her view, one of the best parts of the methodology is using positive framing to support children's behavior rather than focusing on what they shouldn't be doing, which is something prevalent in other school systems.",
        "paragraph6" => "Aleyda enjoys singing and dancing with her students. She loves seeing them laughing and enjoying themselves. She also really loves when her students manage to achieve something that has taken them a while to learn.",
        "paragraph7" => "For her, a good teacher is born from the heart. When a kid, a young person or an adult achieves something, we should also consider it as the achievement of the teachers that paved the way for their learning.",
        "paragraph8" => "We are happy to have Aleyda and so many other wonderful and passionate teachers working with us! Thank you to all the teachers that have taught us throughout our lives, we wouldn’t be the same without you!",
    ], 
    "post2" => [
        "title" => "Sharing the love for Reading",
        "paragraph1" => "In 2019, through the combined effort of partner organizations and incredible supporters, Planting Seeds opened a Community Library in Zone 3 of Guatemala City with the objective of sharing the love of reading to our program participants and community members alike. The program consists of providing a safe place where everyone can come to read and a book-leading program. In a few short years, this Community Library has transformed to provide access to books to not only Zone 3, but all Planting Seeds preschools.",
        "paragraph2" => "This transformation started in 2019, when we launched our “Read With Your Kid” trainings to the parents at our preschools to improve early literacy skills and help foster parent-child relationships. We accompanied these trainings with a weekly bool-lending program at our model school in San Lucas. Now in 2021, we began the year conducting surveys in the preschools to find out the barriers that parents had in taking an active role in the education or their children. The main factors reported by the parents were a lack of experience, confidence and access to books.",
        "paragraph3" => "To combat the lack of experience and confidence parents expressed in the survey, we began providing based parent trainings at our preschools. These trainings are extremely intentional and focus on providing parents with hands-on skills and an opportunity to practice those skills with the teachers and fellow parents. In our “creating little readers” workshop, all parents partnered up and practiced reading to each other as if the other parent was their kid. The parents then received in person feedback from the teachers. Although many parents present difficulties reading or writing themselves, our trainings focus on supporting parents’ ability to read with their kids by telling stories through pictures, adapting to the different needs of all of the Planting Seeds parents.",
        "paragraph4" => "In addition to these trainings, we have begun expanding our Zone 3 Library’s book-lending program to combat the lack of access to books in our rural communities. Now, Planting Seeds students get to borrow four books a month. At the end of each month, parents return the books and the parents return the books and the parents bring a new set. Planting Seeds are so grateful for this program.",
        "paragraph5" => "This growth in our programming is due to our incredibly passionate educators, open and hardworking families, and your generosity. Thank you for all your support. If you have the capacity, you continued help can provide books to families through our Community Library and necessary training to support parents develop a love reading in their households.",
    ], 
    "post3" => [
        "title" => "Mentoring Parents and Students",
        "paragraph1" => "&#34;I feel excited about seeing my students again, even if it's only going to be for a couple of days a week I think this will be especially helpful with certain students that have struggled a lot with remote learning. I feel happy that we will have a chance to work together in the classroom and I'm to guide both students and parents. I think mentoring parents will be beneficial to reinforce the lessons that our students learn at home.&#34; <br>&#34;-Helen Chacón, Preschool teacher at &#34;Garden Seeds of Hope&#34",
        "paragraph2" => "Planting Seeds teachers have gone through a roller-coaster of emotions over the past year. We are so incredibly proud of them! Not only did they adapt to new working conditions in a record time, but they have continued pouring their heart into their work to ensure that our students keep learning despite the different challenging conditions we keep encountering.",
        "paragraph3" => "Over the last year, we have witnessed a significant shift in parents' involvement in their children's education. Helen Chacón, one of our preschool teachers in Tioxya, says that many of the parents she is working with don't know how to read or write; nevertheless, they have put a lot of effort into helping their children. As a teacher, Helen is very motivated to help parents succeed and become effective mentors for their children. Being a teacher in these circumstances is not an easy task. Not everyone has the most appropriate conditions to carry out remote learning, so it has been difficult to ensure that all the activities and information are delivered to both students and parents in the best way possible. However, in a way or another, our teachers have found alternatives to support every household.",
        "paragraph4" => "Helen says that many parents have become more patient and willing to lead educational activities with their children. We are very excited to take this as an opportunity to help parents develop the skills needed to become their children's primary educators.",
    ], 
    
    
];